name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up and build Neutralino.js app
        run: |
          npm install -g @neutralinojs/neu
          neu create neutralino-app
          cp ./resources/icon.png neutralino-app/resources/icons/icon.png
          echo "const icon = '/resources/icons/icon.png'; await Neutralino.window.setIcon(icon); await Neutralino.window.open({url: 'https://leventcord.bsite.net/app', fullscreen: false, width: 800, height: 600, resizable: true});" > neutralino-app/src/js/App.js
          echo '{
              "applicationId": "org.liventcord.app",
              "url": "https://leventcord.bsite.net/app",
              "cli": {"binaryName": "neutralino-app", "resourcesPath": "/resources", "distributionPath": "dist"},
              "modes": {"window": {"title": "LiventCord", "width": 800, "height": 600, "resizable": true, "fullscreen": false}}
          }' > neutralino-app/neutralino.config.json
          cd neutralino-app && neu build --release

      - name: Create and upload zip files
        run: |
          cd neutralino-app/dist/neutralino-app
          for file in *; do zip "../$file.zip" "$file"; done
        working-directory: ./neutralino-app

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app-zips
          path: ./*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: neutralino-app-zips

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          name: Release ${{ github.ref }}
          body: "Release of the Neutralino webview app of liventcord"
          files: ./*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
