name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino Project
        run: |
          neu create neutralino-app
          cd neutralino-app

      - name: Build Neutralino App
        run: |
          cd neutralino-app
          neu build --release

      - name: Debug: Print all contents of current directory
        run: |
          ls -R # Print all contents of the current directory and its subdirectories

      - name: Check dist directory
        run: |
          ls -R neutralino-app/dist  # Debugging step to check contents of dist directory

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: neutralino-app/dist/*  # Ensure path is correct based on the build output

  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub release using GitHub API
        run: |
          TAG_NAME="${{ github.ref_name }}"
          RELEASE_NAME="Release $TAG_NAME"
          BODY="This is the release of the Neutralino app"

          # Create GitHub release using GitHub API
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "'"$TAG_NAME"'", "name": "'"$RELEASE_NAME"'", "body": "'"$BODY"'", "draft": false, "prerelease": false}' \
            https://api.github.com/repos/${{ github.repository }}/releases

      - name: Upload release assets
        run: |
          # Find all the files you want to upload in the dist directory
          for file in neutralino-app/dist/neutralino-app/*; do
            echo "Uploading $file"

            # Upload each file to the release
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -F "file=@$file" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$(basename $file)"
          done
