name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino.js App
        run: |
          neu create neutralino-app

      - name: Customize HTML and JavaScript for Webview
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <title>Webview App</title>
          </head>
          <body>
              <iframe src="https://example.com" style="border:none; width:100vw; height:100vh;"></iframe>
          </body>
          </html>' > neutralino-app/resources/index.html

          echo 'Neutralino.init();' > neutralino-app/resources/js/main.js

      - name: Update Neutralino Config
        run: |
          if [ -f neutralino-app/neutralino.config.json ]; then
            sed -i 's#"url": "http://localhost"#"url": ""#' neutralino-app/neutralino.config.json
            sed -i 's#"enableServer": true#"enableServer": false#' neutralino-app/neutralino.config.json
          else
            echo "neutralino.config.json not found!"
            exit 1
          fi

      - name: Build App
        run: |
          cd neutralino-app
          neu build --release

      - name: Compress Build Artifacts
        run: |
          cd neutralino-app/dist
          zip -r neutralino-app.zip .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: neutralino-app/dist/neutralino-app.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: neutralino-app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          name: Release ${{ github.ref }}
          body: "Release of the Neutralino app with embedded webview for https://example.com."
          files: neutralino-app.zip
          token: ${{ secrets.GITHUB_TOKEN }}
