name: Build and Release LiventCord App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app_url:
        description: 'Application URL'
        required: true
        default: 'https://leventcord.bsite.net/app'
      release_version:
        description: 'Release Version'
        required: true
        default: '1.0.1'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino.js App
        run: |
          neu create liventcord

      - name: Copy custom icon to resources/icons folder
        run: |
          cp ./resources/icon.png liventcord/resources/icons/icon.png

      - name: Create App.js
        run: |
          mkdir -p liventcord/src/js
          echo "const icon = '/resources/icons/icon.png';" > liventcord/src/js/App.js
          echo "await Neutralino.window.setIcon(icon);" >> liventcord/src/js/App.js
          echo "await Neutralino.window.open({url: '${{ github.event.inputs.app_url }}', fullscreen: false, width: 800, height: 600, resizable: true});" >> liventcord/src/js/App.js

      - name: Update Neutralino Config for External URL and Resources Path
        run: |
          if [ -f liventcord/neutralino.config.json ]; then
            echo '{
                "applicationId": "org.liventcord.app",
                "defaultMode": "window",
                "port": 0,
                "url": "${{ github.event.inputs.app_url }}",
                "enableServer": false,
                "nativeAllowList": [
                    "app.*",
                    "os.*",
                    "debug.log"
                ],
                "globalVariables": {},
                "cli": {
                    "binaryName": "liventcord",
                    "resourcesPath": "/resources",
                    "extensionsPath": "/extensions",
                    "distributionPath": "dist"
                },
                "modes": {
                    "window": {
                        "title": "LiventCord",
                        "width": 800,
                        "height": 600,
                        "resizable": true,
                        "fullscreen": false
                    }
                }
            }' > liventcord/neutralino.config.json
          else
            echo "neutralino.config.json not found!"
            exit 1
          fi

      - name: Build App
        run: |
          cd liventcord
          neu build --release

      - name: Set executable permissions for binaries
        run: |
          chmod +x liventcord/dist/liventcord/*

      - name: Create zip files for each platform
        run: |
          cd liventcord/dist/liventcord
          zip liventcord-linux_arm64.zip liventcord-linux_arm64 resources.neu
          zip liventcord-linux_armhf.zip liventcord-linux_armhf resources.neu
          zip liventcord-linux_x64.zip liventcord-linux_x64 resources.neu
          zip liventcord-mac_arm64.zip liventcord-mac_arm64 resources.neu
          zip liventcord-mac_universal.zip liventcord-mac_universal resources.neu
          zip liventcord-mac_x64.zip liventcord-mac_x64 resources.neu
          zip liventcord-win_x64.exe.zip liventcord-win_x64.exe resources.neu

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liventcord-zips
          path: liventcord/dist/liventcord/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: liventcord-zips

      - name: List files to check if zips are present
        run: |
          ls -l

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: Release v${{ github.event.inputs.release_version }}
          body: "Release of the LiventCord webview app"
          files: ./*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
