name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for version tags (e.g., v1.0.0)

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (if your project needs it)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # specify the version your project needs

    - name: Build your app (if applicable)
      run: |
        # Replace this with the actual build command for your project
        npm install
        npm run build

    - name: Create a new release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: "Release ${{ github.ref }}"
        body: "Release of the Neutralino app"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: neutralino-app/neutralino-app/dist/neutralino-app-linux_arm64
        asset_name: neutralino-app-linux_arm64
        asset_content_type: application/octet-stream

    - name: Upload release assets for other platforms
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: neutralino-app/neutralino-app/dist/neutralino-app-linux_armhf
        asset_name: neutralino-app-linux_armhf
        asset_content_type: application/octet-stream

    - name: Upload release assets for Windows
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: neutralino-app/neutralino-app/dist/neutralino-app-win_x64.exe
        asset_name: neutralino-app-win_x64.exe
        asset_content_type: application/octet-stream
