name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino.js App
        run: |
          neu create neutralino-app

      - name: Copy custom icon to resources/icons folder
        run: |
          cp ./resources/icon.png neutralino-app/resources/icons/icon.png

      - name: Create App.js (main entry point)
        run: |
          mkdir -p neutralino-app/src/js
          echo "const icon = '/resources/icons/icon.png';" > neutralino-app/src/js/App.js
          echo "await Neutralino.window.setIcon(icon);" >> neutralino-app/src/js/App.js
          echo "await Neutralino.window.open({url: 'https://leventcord.bsite.net/app', fullscreen: false, width: 800, height: 600, resizable: true});" >> neutralino-app/src/js/App.js

      - name: Update Neutralino Config for External URL and Resources Path
        run: |
          if [ -f neutralino-app/neutralino.config.json ]; then
            echo '{
                "applicationId": "org.liventcord.app",
                "defaultMode": "window",
                "port": 0,
                "url": "https://leventcord.bsite.net/app",
                "enableServer": true,
                "nativeAllowList": [
                    "app.*",
                    "os.*",
                    "debug.log"
                ],
                "globalVariables": {},
                "cli": {
                    "binaryName": "neutralino-app",
                    "resourcesPath": "/resources",
                    "extensionsPath": "/extensions",
                    "distributionPath": "dist"
                },
                "modes": {
                    "window": {
                        "title": "LiventCord",
                        "width": 800,
                        "height": 600,
                        "resizable": true,
                        "fullscreen": false
                    }
                }
            }' > neutralino-app/neutralino.config.json
          else
            echo "neutralino.config.json not found!"
            exit 1
          fi

      - name: Build App
        run: |
          cd neutralino-app
          neu build --release

      - name: Compress and Prepare Platform-specific Zip Files
        run: |
          cd neutralino-app/dist
          # Ensure the directories and files exist before zipping
          zip -r neutralino-app-linux_arm64.zip neutralino-app-linux_arm64 || echo "neutralino-app-linux_arm64.zip not found"
          zip -r neutralino-app-linux_x64.zip neutralino-app-linux_x64 || echo "neutralino-app-linux_x64.zip not found"
          zip -r neutralino-app-linux_armhf.zip neutralino-app-linux_armhf || echo "neutralino-app-linux_armhf.zip not found"
          zip -r neutralino-app-mac_arm64.zip neutralino-app-mac_arm64 || echo "neutralino-app-mac_arm64.zip not found"
          zip -r neutralino-app-mac_universal.zip neutralino-app-mac_universal || echo "neutralino-app-mac_universal.zip not found"
          zip -r neutralino-app-mac_x64.zip neutralino-app-mac_x64 || echo "neutralino-app-mac_x64.zip not found"
          zip -r neutralino-app-win_x64.zip neutralino-app-win_x64.exe || echo "neutralino-app-win_x64.zip not found"
          zip -r resources.neu.zip resources.neu || echo "resources.neu.zip not found"

      - name: Upload Platform-specific Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: |
            neutralino-app/dist/neutralino-app-linux_arm64.zip
            neutralino-app/dist/neutralino-app-linux_x64.zip
            neutralino-app/dist/neutralino-app-linux_armhf.zip
            neutralino-app/dist/neutralino-app-mac_arm64.zip
            neutralino-app/dist/neutralino-app-mac_universal.zip
            neutralino-app/dist/neutralino-app-mac_x64.zip
            neutralino-app/dist/neutralino-app-win_x64.zip
            neutralino-app/dist/resources.neu.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: neutralino-app

      - name: List downloaded artifact files
        run: |
          ls -l

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          name: Release ${{ github.ref }}
          body: "Release of the Neutralino webview app of liventcord"
          files: |
            neutralino-app-linux_arm64.zip
            neutralino-app-linux_x64.zip
            neutralino-app-linux_armhf.zip
            neutralino-app-mac_arm64.zip
            neutralino-app-mac_universal.zip
            neutralino-app-mac_x64.zip
            neutralino-app-win_x64.zip
            resources.neu.zip
          token: ${{ secrets.GITHUB_TOKEN }}
