name: Build and Release Neutralino.js Client

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino.js App
        run: |
          neu create neutralino-app

      - name: Copy custom icon to resources folder
        run: |
          cp ./resources/icon.png neutralino-app/resources/icon.png

      - name: Update Neutralino Config for External URL and Icon
        run: |
          if [ -f neutralino-app/neutralino.config.json ]; then
            echo '{
                "applicationId": "org.yourdomain.app",
                "defaultMode": "window",
                "port": 0,
                "url": "https://leventcord.bsite.net/app",
                "enableServer": true,
                "nativeAllowList": [
                    "app.*",
                    "os.*",
                    "debug.log"
                ],
                "globalVariables": {},
                "cli": {
                    "binaryName": "neutralino-app",
                    "resourcesPath": "/resources",
                    "extensionsPath": "/extensions",
                    "distributionPath": "dist"
                },
                "modes": {
                    "window": {
                        "title": "Neutralino.js Webview App",
                        "width": 800,
                        "height": 600,
                        "resizable": true,
                        "fullscreen": false,
                        "icon": "/resources/icon.png"
                    }
                }
            }' > neutralino-app/neutralino.config.json
          else
            echo "neutralino.config.json not found!"
            exit 1
          fi

      - name: Build App
        run: |
          cd neutralino-app
          neu build --release

      - name: Compress Build Artifacts
        run: |
          cd neutralino-app/dist
          zip -r neutralino-app.zip .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: neutralino-app/dist/neutralino-app.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: neutralino-app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          name: Release ${{ github.ref }}
          body: "Release of the liventcord client"
          files: neutralino-app.zip
          token: ${{ secrets.GITHUB_TOKEN }}
