name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  create_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the action can create and push releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build your app
        run: |
          npm install
          npm run build

      - name: Create a new release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          body: "Release of the Neutralino app"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: neutralino-app/neutralino-app/dist/neutralino-app-linux_arm64
          asset_name: neutralino-app-linux_arm64
          asset_content_type: application/octet-stream
