name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino.js App
        run: |
          neu create neutralino-app

      - name: Copy custom icon to resources/icons folder
        run: |
          cp ./resources/icon.png neutralino-app/resources/icons/icon.png

      - name: Copy App.js from repository to Neutralino app
        run: |
          mkdir -p neutralino-app/src/js
          cp ./src/js/App.js neutralino-app/src/js/App.js

      - name: Update Neutralino Config for External URL and Resources Path
        run: |
          if [ -f neutralino-app/neutralino.config.json ]; then
            echo '{
                "applicationId": "org.liventcord.app",
                "defaultMode": "window",
                "port": 0,
                "url": "https://leventcord.bsite.net/app",
                "enableServer": false,
                "nativeAllowList": [
                    "app.*",
                    "os.*",
                    "debug.log"
                ],
                "globalVariables": {},
                "cli": {
                    "binaryName": "neutralino-app",
                    "resourcesPath": "/resources",
                    "extensionsPath": "/extensions",
                    "distributionPath": "dist"
                },
                "modes": {
                    "window": {
                        "title": "LiventCord",
                        "width": 800,
                        "height": 600,
                        "resizable": true,
                        "fullscreen": false
                    }
                }
            }' > neutralino-app/neutralino.config.json
          else
            echo "neutralino.config.json not found!"
            exit 1
          fi

      - name: Build App
        run: |
          cd neutralino-app
          neu build --release

      - name: Make binaries executable
        run: |
          chmod +x neutralino-app/dist/neutralino-app/neutralino-app-linux_arm64
          chmod +x neutralino-app/dist/neutralino-app/neutralino-app-linux_armhf
          chmod +x neutralino-app/dist/neutralino-app/neutralino-app-linux_x64
          chmod +x neutralino-app/dist/neutralino-app/neutralino-app-mac_arm64
          chmod +x neutralino-app/dist/neutralino-app/neutralino-app-mac_universal
          chmod +x neutralino-app/dist/neutralino-app/neutralino-app-mac_x64
          chmod +x neutralino-app/dist/neutralino-app/neutralino-app-win_x64.exe

      - name: Create zip files for each platform and include config and neu files
        run: |
          zip neutralino-app-linux_arm64.zip neutralino-app/dist/neutralino-app/neutralino-app-linux_arm64 neutralino-app/neutralino.config.json neutralino-app/dist/neutralino-app/resources.neu
          zip neutralino-app-linux_armhf.zip neutralino-app/dist/neutralino-app/neutralino-app-linux_armhf neutralino-app/neutralino.config.json neutralino-app/dist/neutralino-app/resources.neu
          zip neutralino-app-linux_x64.zip neutralino-app/dist/neutralino-app/neutralino-app-linux_x64 neutralino-app/neutralino.config.json neutralino-app/dist/neutralino-app/resources.neu
          zip neutralino-app-mac_arm64.zip neutralino-app/dist/neutralino-app/neutralino-app-mac_arm64 neutralino-app/neutralino.config.json neutralino-app/dist/neutralino-app/resources.neu
          zip neutralino-app-mac_universal.zip neutralino-app/dist/neutralino-app/neutralino-app-mac_universal neutralino-app/neutralino.config.json neutralino-app/dist/neutralino-app/resources.neu
          zip neutralino-app-mac_x64.zip neutralino-app/dist/neutralino-app/neutralino-app-mac_x64 neutralino-app/neutralino.config.json neutralino-app/dist/neutralino-app/resources.neu
          zip neutralino-app-win_x64.exe.zip neutralino-app/dist/neutralino-app/neutralino-app-win_x64.exe neutralino-app/neutralino.config.json neutralino-app/dist/neutralino-app/resources.neu
          zip resources.neu.zip neutralino-app/dist/neutralino-app/resources.neu

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app-zips
          path: ./*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: neutralino-app-zips

      - name: List files to check if zips are present
        run: |
          ls -l

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          body: "Release of the Neutralino webview app of liventcord"
          files: ./*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
