name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino.js App
        run: |
          neu create neutralino-app

      - name: Copy custom icon to resources/icons folder
        run: |
          cp ./resources/icon.png neutralino-app/resources/icons/icon.png

      - name: Create App.js (main entry point)
        run: |
          mkdir -p neutralino-app/src/js
          echo "const icon = '/resources/icons/icon.png';" > neutralino-app/src/js/App.js
          echo "await Neutralino.window.setIcon(icon);" >> neutralino-app/src/js/App.js
          echo "await Neutralino.window.open({url: 'https://leventcord.bsite.net/app', fullscreen: false, width: 800, height: 600, resizable: true});" >> neutralino-app/src/js/App.js

      - name: Update Neutralino Config for External URL and Resources Path
        run: |
          if [ -f neutralino-app/neutralino.config.json ]; then
            echo '{
                "applicationId": "org.liventcord.app",
                "defaultMode": "window",
                "port": 0,
                "url": "https://leventcord.bsite.net/app",
                "enableServer": true,
                "nativeAllowList": [
                    "app.*",
                    "os.*",
                    "debug.log"
                ],
                "globalVariables": {},
                "cli": {
                    "binaryName": "neutralino-app",
                    "resourcesPath": "/resources",
                    "extensionsPath": "/extensions",
                    "distributionPath": "dist"
                },
                "modes": {
                    "window": {
                        "title": "LiventCord",
                        "width": 800,
                        "height": 600,
                        "resizable": true,
                        "fullscreen": false
                    }
                }
            }' > neutralino-app/neutralino.config.json
          else
            echo "neutralino.config.json not found!"
            exit 1
          fi

      - name: Build App
        run: |
          cd neutralino-app
          neu build --release

      - name: Extract Build Artifacts
        run: |
          cd neutralino-app/dist
          mkdir extracted
          unzip neutralino-app.zip -d extracted/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: neutralino-app/dist/extracted/**

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: neutralino-app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          name: Release ${{ github.ref }}
          body: "Release of the Neutralino webview app of liventcord"
          files: neutralino-app.zip
          token: ${{ secrets.GITHUB_TOKEN }}
