name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Clean up previous app directory (if exists)
        run: |
          rm -rf neutralino-app

      - name: Create Neutralino Project
        run: |
          neu create neutralino-app
          cd neutralino-app

      - name: Modify the Neutralino Config
        run: |
          echo '{
            "applicationId": "com.example.neutrolinoapp",
            "version": "1.0.0",
            "defaultWidth": 800,
            "defaultHeight": 600,
            "port": 0,
            "url": "https://example.com",
            "window": {
              "title": "NeutralinoApp",
              "resizable": true
            },
            "logging": {
              "enabled": true
            },
            "cli": {
              "distributionPath": "dist"
            }
          }' > neutralino-app/neutralino.config.json

      - name: Build Neutralino App
        run: |
          cd neutralino-app
          neu build --release

      - name: Verify dist contents
        run: |
          ls -R neutralino-app/dist

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: neutralino-app/dist/*  # Path to the distribution directory after build

  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}  # Correct 'name' input
          body: "This is the release of the Neutralino app"
          draft: false
          prerelease: false
          files: neutralino-app/dist/*  # Correct 'files' input

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: neutralino-app/dist/*  # Path to the built assets in the dist directory
