name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu

      - name: Create Neutralino Project
        run: |
          neu create neutralino-app
          cd neutralino-app

      - name: Build Neutralino App
        run: |
          cd neutralino-app
          neu build --release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: neutralino-app/dist/*

  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}  # Corrected input for release name
          body: "This is the release of the Neutralino app"
          files: neutralino-app/dist/*  # Ensure the path is correct for your built assets

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: neutralino-app/dist/*  # Path to the built artifact
          asset_name: neutralino-app-linux.zip  # Customize based on platform or needs
          asset_content_type: application/zip
