name: Build and Release Neutralino.js App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and install Neutralino CLI
        run: |
          npm install -g @neutralinojs/neu
          neu create neutralino-app
          cd neutralino-app
          neu build --release

      - name: Check build directory
        run: ls -R neutralino-app

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: neutralino-app
          path: neutralino-app/*  # This uploads all files in the neutralino-app folder

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: neutralino-app

      - name: List downloaded files
        run: ls -R neutralino-app

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          name: Release ${{ github.ref }}
          body: "Release of the Neutralino app"
          files: neutralino-app/*  # Corrected path to files in the neutralino-app folder
          token: ${{ secrets.GITHUB_TOKEN }}
